### ISSUE TITLE
Catalogus API toont ook concept zaaktypen bij de catalogus resource als inline

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#1335]
# Bug

Dit moet niet, want standaard moeten alleen de zaaktypen met status=definitief getoond worden. Hetzelfde geldt waarschijnlijk voor alle "inlines".

**Comment by annashamray** [comment]
@sergei-maertens @joeribekker @stevenbal Let's discuss the logic of `concept` objects

If the type (`zaaktype`, `besluittype` or `informatieobjecttype`) has concept = True **as is**:
* you can
    * see it in related Catalogus API (as inlines)
    * see it in related types API  (as inlines)
    * create M2M relations between types (and you can do it **only** if concept = True)
    * create related object (zaak, besluit or informatieobject)
    * create relations between zaak, besluit or informatieobject in reference implementation

* you can't
   * see types in their API in default LIST action (without parameters)
   * create relations between `zaak`, `besluit` or `informatieobject` in `open-zaak`

**How should we change it?** 
1. Should we hide unpublished types from their related types API (in inlines)? If yes how the client will know that there is M2M relations between concept types? Because it'is impossible to create M2M relations if types are published.
For example, I created a `zaaktype`, which I left unpublished (concept=True), because I want to create a related `besluittype`. But when I create `besluittype` with the `zaaktype` in `zaaktypes` attribute, the returned result will have empty `zaaktypes` list, because it's concept = True
And I think it's really had to implement this type of behavior
1. If we still want to hide unpublished types from their related types API should we allow creating M2M relations between non-concept types, which is forbidden now? 
1. Should we forbid creating objects ( `zaak`, `besluit` and `informatieobject`) based on types with concept = True (related issue - https://github.com/VNG-Realisatie/gemma-zaken/issues/1337)
1. Should we forbid creating relations between objects in reference implementation?

**Comment by annashamray** [comment]
request for clarification in https://github.com/VNG-Realisatie/gemma-zaken/issues/1335#issuecomment-535437660

**Comment by michielverhoef** [comment]
> Dit moet niet, want standaard moeten alleen de zaaktypen met status=definitief getoond worden. Hetzelfde geldt waarschijnlijk voor alle "inlines".

Hoezo? Is dat niet een specifieke uitvraag voor een bepaald doeleinde? Bv. voor welke zaaktypen kan ik een zaak aanmaken?

Wat als ik nu wil kunnen zien welke zaaktypes er in een catalogus opgenomen zijn, het liefst gegroepeerd op status (concept of niet). Bijvoorbeeld wanneer ik de volledige catalogus wil opvragen in een catalogus beheer applicatie.

De aanname die door Joeri met veel stelligheid beweerd wordt hoeft helemaal niet waar te zijn (is dat volgens mij ook niet) en minimaal moet er door de PO iets over gezegd worden.

**Comment by Hugo-ter-Doest** [comment]
I think we should make a distinction between design time (editing the catalog) and runtime (creating objects like zaak or besluit that refer to types). If you want to edit the catalog it should be possible to work with types that have concept=true. When creating instances like zaak, besluit, etc. you cannot use types with concept=true.

So, depending on what you are doing, you want or don't want to see types with concept=True.

1. This is design time: so we should see concept types. 
2. N.a. because of 1
3. Yes, creating objects using types that are concept should be forbidden.
4. No, it is necessary to create relations between types

**Comment by joeribekker** [comment]
I discussed this with @Hugo-ter-Doest and @michielverhoef, to clarify this bug, and came with the following solution:

1. It should *not* be possible to set `concept=False` (ie. publish) a `Zaaktype` if there are relations to an unpublished (ie. concept=True) object, like an `InformatieObjectType` or `BesluitType`. If this is the case, the API should return a HTTP 400.

NOTE: It should still be possible to publish `InformatieObjectType` or `BesluitType` even if they have a relation to a `Zaaktype` that is still in concept. We consider `Zaaktype` as the leading/main object.

2. Inlines should work as they work now. This means: If I get a `Zaaktype` (with `?status=concept`) that has `concept=True`, it can show `InformatieObjectTypes` that have `concept=False`. This is not a problem.

Due to 1, it can **not** occur that you get a `Zaaktype` (with `?status=published`) that has `concept=False`, to show an `InformatieObjectType` that has `concept=True`.

So, in essence, we need to make 1 change, as described in 1).

**Comment by annashamray** [comment]
@joeribekker 
In addition we forbid creating `zaak`, `besluit` and `informatieobject` objects based on unpublished types, right?

**Comment by joeribekker** [comment]
Oh, the other API's?

Yes, you are correct! Each API should check if the type is **not** a concept and otherwise forbid the creation!

Good call!

**Comment by stevenbal** [comment]
@joeribekker @annashamray I've made issues for this in gemma-zaken and open-zaak https://github.com/VNG-Realisatie/gemma-zaken/issues/1363

**Comment by annashamray** [comment]
@stevenbal I think it duplicates https://github.com/VNG-Realisatie/gemma-zaken/issues/1337

**Comment by stevenbal** [comment]
@annashamray oh I didn't see that one, but I believe that this logic should apply to all resources outside of ZTC, not just `Zaak`, `Besluit` and `Informatieobject`, but also `Autorisaties` for instance right?

**Comment by annashamray** [comment]
@stevenbal sorry I don't get your point. 

Only 3 ZTC resources have this `concept` support - `Zaaktype`, `Besluittype` and `Informatieobjecttype` and the creation of only three resources outside ZTC depends on them - `Zaak`, `Besluit` and `Informatieonbject`.
I can't see how the creation of `Resultaat` can be affected since it depends on `Zaak`, which passed all the checks during its creation.

**Comment by stevenbal** [comment]
@annashamray ah yes, you're right, I forgot about that dependency for a second

**Comment by joeribekker** [comment]
Opgelost in gerelateerd PR.
