### ISSUE TITLE
Zaak/Besluit identificatie staat niet alfanumerieke waardes toe via de API

### ISSUE THREAD

**Issue by stevenbal** [VNG-Realisatie/gemma-zaken#1790]
# Bug

Als ik in de Besluiten API en de Zaken API een `Besluit` of een `Zaak` aanmaak met een `identificatie` die niet-alfanumerieke tekens bevat (spaties bijv.), dan slaagt het aanmaken.

```
POST /api/v1/zaken

{
    "url": "http://172.17.0.1:8000/api/v1/zaken/0a65623f-d9e4-4b6d-9e2a-042fa5eb12af",
    "uuid": "0a65623f-d9e4-4b6d-9e2a-042fa5eb12af",
    "identificatie": "foo a b",
    "bronorganisatie": "000000000",
    "omschrijving": "string",
    "toelichting": "string",
    "zaaktype": "http://172.17.0.1:8002/api/v1/zaaktypen/4db8dc7d-fe22-4ebb-81ee-e87e8c4deafd",
    "registratiedatum": "2019-04-09",
    "verantwoordelijkeOrganisatie": "000000000",
    "startdatum": "2019-04-09",
    "einddatum": null,
    "einddatumGepland": "2019-04-20",
    "uiterlijkeEinddatumAfdoening": "2019-04-09",
    "publicatiedatum": "2019-04-09",
    "communicatiekanaal": "",
    "productenOfDiensten": [],
    "vertrouwelijkheidaanduiding": "openbaar",
    "betalingsindicatie": "geheel",
    "betalingsindicatieWeergave": "De met de zaak gemoeide kosten zijn geheel betaald.",
    "laatsteBetaaldatum": null,
    "zaakgeometrie": {
        "type": "Point",
        "coordinates": [
            53.0,
            5.0
        ]
    },
    "verlenging": {
        "reden": "",
        "duur": null
    },
    "opschorting": {
        "indicatie": true,
        "reden": "string"
    },
    "selectielijstklasse": "https://referentielijsten-api.vng.cloud/api/v1/resultaten/33400fb3-607f-4f63-a11f-fc34d87a8826",
    "hoofdzaak": null,
    "deelzaken": [],
    "relevanteAndereZaken": [],
    "eigenschappen": [],
    "status": null,
    "kenmerken": [],
    "archiefnominatie": null,
    "archiefstatus": "nog_te_archiveren",
    "archiefactiedatum": null,
    "resultaat": null
}
```
Als ik dan vervolgens in de admin probeer aanpassingen te maken aan deze Zaak en op `Opslaan` druk, komt de eerder gekozen `identificatie` niet door de validatie heen:

![image](https://user-images.githubusercontent.com/29249171/114186649-661f7f00-9947-11eb-8657-c1eb68500642.png)

De API moet net als de admin valideren op enkel alfanumerieke karakters (dit gaat overigens wel goed voor `EnkelvoudigInformatieObject` en `ZaakType` via de API)

**Comment by sergei-maertens** [comment]
In my opinion, it should be the other way around. The API allows non-alphanumeric values, and I don't see what's wrong with that. The most important thing is that spaces can now be used, and _are_ used in some environments.

I believe the admin validation should be relaxed so that it allows spaces as well (and other non-alphanumeric characters).

Argumentation for this is two-fold:

1. Migrating existing values, and existing communicated identificaties (removing spaces) is a breaking change and impacts systems making use of these API's, even if we don't know what exactly they store. If they save zaak(type) identificaties, all those records also need to be updated and there is a risk of collisions. For me, that's not acceptable.
2. The constraint (only alpha-numeric) was based on RGBZ, but I don't actually see any human or technical basis _why_ this should be constrained. What's wrong with using spaces in identifications?

**Comment by michielverhoef** [comment]
Ik ben het eens met  @sergei-maertens. 
Dit is een bug in de admin interface van de Zaken API. Mogelijk ook van de andere referentie implementaties, Documenten, Catalogi, Besluiten?
