### ISSUE TITLE
Cetificate problem with https://referentielijsten-api.vng.cloud/api/v1/ 

### ISSUE THREAD

**Issue by annashamray** [VNG-Realisatie/gemma-zaken#2267]
# Bug

It looks like certificates are not valid for https://referentielijsten-api.vng.cloud/api/v1/ 
When you try to access it from browser or with curl you have error: 

> SSL certificate problem: self-signed certificate

**Comment by joerivrij** [comment]
That url is no longer valid (and gives a 404)

https://referentielijsten-api.vng.cloud/api/v1/resultaten or https://referentielijsten-api.vng.cloud/api/v1/schema work fine both with curl and in the browser. 

You might have hit the endpoint during an upgrade and since vrl is down at that time it gives a pretty weird looking error since it hits the default traefik endpoint.

**Comment by joerivrij** [comment]
If you are looking for a health endpoint please use:

https://referentielijsten-api.vng.cloud/api/v1/health

**Comment by annashamray** [comment]
Thank you! Now everything works
