### ISSUE TITLE
[VRAAG] How to fill `ZaakObjectType.catalogus` property

### ISSUE THREAD

**Issue by annashamray** [VNG-Realisatie/gemma-zaken#2330]
In the Catalogi API `ZaakObjectType` resource has two required properties `catalogus` and `zaaktype`. 
Can `catalogus` be different from `zaaktype.catalogus`? If no why is it property writeable and required?

**Comment by michielverhoef** [comment]
Hmm, this sounds like a small bug to me because all types (Zaaktype, Statustype, Zaakobjecttype etc.) should be in the same Catalogus. For convenience the catalogus is included in the GET operations so a consumer does not have to query Zaaktype to find out the Catalogus of a Statustype/Roltype etc.  

So the property was intended as read-only and derived from the Zaaktype.

**Comment by annashamray** [comment]
Thanks for the fast response! It's clear now!
